leftnav:
- identifier: 094bc7b2-4a93-e593-51b1-74436a2320e5
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 1f1c79f9-8454-d0dc-c4de-8d02d0059c45
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 24b76a0d-695c-c1d7-bc81-9bb2950a852c
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 30
- identifier: f157b1e4-bfe3-ec78-d5cf-02ca3f4a25d3
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: 31b4d2ac-00d8-ddbb-a570-3b5e14313422
  name: Exams
  pageRef: /pages/exams
  weight: 50
